/// Flutter icons Facebook
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Facebook
///      fonts:
///       - asset: fonts/Facebook.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class Facebook {
  Facebook._();

  static const _kFontFam = 'Facebook';
  static const IconData twitter = const IconData(0xf309, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf30c, fontFamily: _kFontFam);
  static const IconData gplus = const IconData(0xf30f, fontFamily: _kFontFam);
}
